Plik dziennika [ 03/01/2018 ]
---------------------------------------

+ [20:43:54][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #13]: Wystąpił błąd połączenia [0] []
+ [20:45:11][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #13]: Wystąpił błąd połączenia [0] []
+ [20:52:09][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #12]: Wystąpił błąd połączenia [] [php_network_getaddresses: getaddrinfo failed: Nieznany host. ]
+ [20:52:53][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #12]: Wystąpił błąd połączenia [] [php_network_getaddresses: getaddrinfo failed: Nieznany host. ]
+ [20:54:52][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #12]: Wystąpił błąd połączenia11C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php
+ [20:56:15][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #12]: Wystąpił błąd połączenia 2002php_network_getaddresses: getaddrinfo failed: Nieznany host. 
+ [21:02:11][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #14]: Wystąpił błąd połączenia:2002php_network_getaddresses: getaddrinfo failed: Nieznany host. 
+ [21:05:04][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #12]: Wystąpił błąd połączenia:2002php_network_getaddresses: getaddrinfo failed: Nieznany host. 
+ [22:41:26][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #51]: Wystąpił błąd połączenia [] [ ]
+ [23:01:54][::1][plik C:\WebServ\httpd\kolekcjoner\Managers\DatabaseManager.php][linia #51]: Wystąpił błąd połączenia [] [ ]
